Repository tidbyt/community, pull requests merged in 2022-04, with the labels that each got.

#291 New App: Duolingo dashboard 🦉
  apps/apps.go
  apps/duolingo/README.md
  apps/duolingo/dayview.png
  apps/duolingo/duolingo.go
  apps/duolingo/duolingo.star
  apps/duolingo/twoweekview.png
  apps/duolingo/weekview.png
Labels: waiting on author

#317 Optionally show just Sunrise or Sunset or both in Sunrisesunset
  apps/sunrisesunset/sunrise_sunset.star
Labels: waiting on original author

#296 New App: Finevent
  apps/apps.go
  apps/finevent/finevent.go
  apps/finevent/finevent.star
Labels: waiting on author

#306 Add Surflive app
  apps/apps.go
  apps/surflive/surflive.go
  apps/surflive/surflive.star
Labels: waiting on author

#313 New Look, Stepcounter
  apps/stepcounter/step_counter.star
  apps/stepcounter/stepcounter.go
  apps/stepcounter/stepcounter.star
  apps/stepcounter/stepcounter_weekly.png
Labels: waiting on Tidbyt team
