Repository tidbyt/community, pull requests merged in 2022-09, with the labels that each got.

#625 SF NextMuni Updates
  apps/sfnextmuni/sf_next_muni.star
Labels: waiting on original author

#635 Add LeetCode stats app
  apps/apps.go
  apps/leetcodestats/README.md
  apps/leetcodestats/leetcodestats.go
  apps/leetcodestats/leetcodestats.star
  apps/leetcodestats/screenshot.png
Labels: waiting on author

#644 Add HEX Daily Stats app
  apps/hexdailystats/README.md
  apps/hexdailystats/hex_daily_stats.star
  apps/hexdailystats/hexdailystats.go
  apps/hexdailystats/screenshot.png
Labels: waiting on author

#634 feat: Add Textbyt applet
  apps/apps.go
  apps/textbyt/README.md
  apps/textbyt/messages.png
  apps/textbyt/textbyt.go
  apps/textbyt/textbyt.star
Labels: waiting on author

#560 New app: Amazing
  apps/amazing/amazing.go
  apps/amazing/amazing.star
  apps/amazing/backtracking.webp
  apps/amazing/randomized_kruskal.webp
  apps/amazing/recursive_division.webp
  apps/apps.go
Labels: waiting on Tidbyt team
